name: CI Basic Workflow

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.12.0'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: |
          yarn lint || exit 1

      - name: Build core Models
        run: yarn build-core-models

      - name: Build core API
        run: yarn build-core-api

      - name: Build core API resolver
        run: yarn build-core-api-resolver

      - name: Build core Keycloak
        run: yarn build-core-keycloak

      - name: Run tests
        run: yarn test

      - name: verify build output
        run: |
          ls dist/
